name: CMake Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        preset: [debug, release, debug-vcpkg, release-vcpkg]
        
    runs-on: ${{ matrix.os }}
    
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2
      with:
        submodules: 'recursive'
    
    - name: Export GitHub Actions cache environment variables
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: Setup CMake
      uses: threeal/cmake-action@v2.1.0
      
    - name: Setup vcpkg
      if: contains(matrix.preset, 'vcpkg')
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: '' # Uses the baseline from vcpkg.json
      
    - name: Set VCPKG_ROOT Environment Variable
      if: contains(matrix.preset, 'vcpkg')
      shell: bash
      run: |
        if [ "${{ runner.os }}" == "Windows" ]; then
          echo "VCPKG_ROOT=${{ github.workspace }}/vcpkg" >> $GITHUB_ENV
        else 
          echo "VCPKG_ROOT=${{ github.workspace }}/vcpkg" >> $GITHUB_ENV
        fi
    
    - name: Configure CMake
      uses: threeal/cmake-action@v2.1.0
      with:
        run-build: false
        args: --preset ${{ matrix.preset }}
        
    - name: Build
      uses: threeal/cmake-action@v2.1.0
      with:
        build-args: --preset ${{ matrix.preset }}
